/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Appointment model module.
* @module model/Appointment
* @version V1.0
*/
export default class Appointment {
    /**
    * Constructs a new <code>Appointment</code>.
    * @alias module:model/Appointment
    * @class
    * @param endDate {Date} 
    * @param startDate {Date} 
    * @param title {String} 
    */

    constructor(endDate, startDate, title) {
        

        
        

        this['end_date'] = endDate;this['start_date'] = startDate;this['title'] = title;

        
    }

    /**
    * Constructs a <code>Appointment</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Appointment} obj Optional instance to populate.
    * @return {module:model/Appointment} The populated <code>Appointment</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Appointment();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('remind_time')) {
                obj['remind_time'] = ApiClient.convertToType(data['remind_time'], 'Number');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Date} end_date
    */
    end_date = undefined;
    /**
    * @member {String} location
    */
    location = undefined;
    /**
    * @member {Number} remind_time
    */
    remind_time = undefined;
    /**
    * @member {Date} start_date
    */
    start_date = undefined;
    /**
    * @member {String} title
    */
    title = undefined;








}


