/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Appointment from './Appointment';





/**
* The AppointmentStatus model module.
* @module model/AppointmentStatus
* @version V1.0
*/
export default class AppointmentStatus {
    /**
    * Constructs a new <code>AppointmentStatus</code>.
    * @alias module:model/AppointmentStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AppointmentStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AppointmentStatus} obj Optional instance to populate.
    * @return {module:model/AppointmentStatus} The populated <code>AppointmentStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppointmentStatus();

            
            
            

            if (data.hasOwnProperty('appointment')) {
                obj['appointment'] = Appointment.constructFromObject(data['appointment']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Appointment} appointment
    */
    appointment = undefined;
    /**
    * @member {module:model/AppointmentStatus.StatusEnum} status
    */
    status = undefined;






    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
    
        /**
         * value: "CREATED"
         * @const
         */
        "CREATED": "CREATED",
    
        /**
         * value: "UPDATED"
         * @const
         */
        "UPDATED": "UPDATED",
    
        /**
         * value: "DELETED"
         * @const
         */
        "DELETED": "DELETED"    
    };



}


