/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AppointmentStatus from './AppointmentStatus';





/**
* The AppointmentStatusList model module.
* @module model/AppointmentStatusList
* @version V1.0
*/
export default class AppointmentStatusList {
    /**
    * Constructs a new <code>AppointmentStatusList</code>.
    * @alias module:model/AppointmentStatusList
    * @class
    * @param syncToken {String} 
    */

    constructor(syncToken) {
        

        
        

        this['sync_token'] = syncToken;

        
    }

    /**
    * Constructs a <code>AppointmentStatusList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AppointmentStatusList} obj Optional instance to populate.
    * @return {module:model/AppointmentStatusList} The populated <code>AppointmentStatusList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppointmentStatusList();

            
            
            

            if (data.hasOwnProperty('appointment_statuses')) {
                obj['appointment_statuses'] = ApiClient.convertToType(data['appointment_statuses'], [AppointmentStatus]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('sync_token')) {
                obj['sync_token'] = ApiClient.convertToType(data['sync_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/AppointmentStatus>} appointment_statuses
    */
    appointment_statuses = undefined;
    /**
    * @member {Number} count
    */
    count = undefined;
    /**
    * @member {String} next
    */
    next = undefined;
    /**
    * @member {String} previous
    */
    previous = undefined;
    /**
    * @member {String} sync_token
    */
    sync_token = undefined;








}


