/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Campaign from './Campaign';





/**
* The CampaignList model module.
* @module model/CampaignList
* @version V1.0
*/
export default class CampaignList {
    /**
    * Constructs a new <code>CampaignList</code>.
    * @alias module:model/CampaignList
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CampaignList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CampaignList} obj Optional instance to populate.
    * @return {module:model/CampaignList} The populated <code>CampaignList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CampaignList();

            
            
            

            if (data.hasOwnProperty('campaigns')) {
                obj['campaigns'] = ApiClient.convertToType(data['campaigns'], [Campaign]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Campaign>} campaigns
    */
    campaigns = undefined;
    /**
    * @member {Number} count
    */
    count = undefined;
    /**
    * @member {String} next
    */
    next = undefined;
    /**
    * @member {String} previous
    */
    previous = undefined;








}


