/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Goal from './Goal';
import Sequence from './Sequence';





/**
* The Campaign model module.
* @module model/Campaign
* @version V1.0
*/
export default class Campaign {
    /**
    * Constructs a new <code>Campaign</code>.
    * @alias module:model/Campaign
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Campaign</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Campaign} obj Optional instance to populate.
    * @return {module:model/Campaign} The populated <code>Campaign</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Campaign();

            
            
            

            if (data.hasOwnProperty('active_contact_count')) {
                obj['active_contact_count'] = ApiClient.convertToType(data['active_contact_count'], 'Number');
            }
            if (data.hasOwnProperty('completed_contact_count')) {
                obj['completed_contact_count'] = ApiClient.convertToType(data['completed_contact_count'], 'Number');
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
            if (data.hasOwnProperty('goals')) {
                obj['goals'] = ApiClient.convertToType(data['goals'], [Goal]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('published_date')) {
                obj['published_date'] = ApiClient.convertToType(data['published_date'], 'Date');
            }
            if (data.hasOwnProperty('published_status')) {
                obj['published_status'] = ApiClient.convertToType(data['published_status'], 'Boolean');
            }
            if (data.hasOwnProperty('published_time_zone')) {
                obj['published_time_zone'] = ApiClient.convertToType(data['published_time_zone'], 'String');
            }
            if (data.hasOwnProperty('sequences')) {
                obj['sequences'] = ApiClient.convertToType(data['sequences'], [Sequence]);
            }
            if (data.hasOwnProperty('time_zone')) {
                obj['time_zone'] = ApiClient.convertToType(data['time_zone'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} active_contact_count
    */
    active_contact_count = undefined;
    /**
    * @member {Number} completed_contact_count
    */
    completed_contact_count = undefined;
    /**
    * @member {Date} date_created
    */
    date_created = undefined;
    /**
    * @member {String} error_message
    */
    error_message = undefined;
    /**
    * @member {Array.<module:model/Goal>} goals
    */
    goals = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Date} published_date
    */
    published_date = undefined;
    /**
    * @member {Boolean} published_status
    */
    published_status = undefined;
    /**
    * @member {String} published_time_zone
    */
    published_time_zone = undefined;
    /**
    * @member {Array.<module:model/Sequence>} sequences
    */
    sequences = undefined;
    /**
    * @member {String} time_zone
    */
    time_zone = undefined;








}


