/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CheckListItemDetails model module.
* @module model/CheckListItemDetails
* @version V1.0
*/
export default class CheckListItemDetails {
    /**
    * Constructs a new <code>CheckListItemDetails</code>.
    * @alias module:model/CheckListItemDetails
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CheckListItemDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CheckListItemDetails} obj Optional instance to populate.
    * @return {module:model/CheckListItemDetails} The populated <code>CheckListItemDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckListItemDetails();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('done_date')) {
                obj['done_date'] = ApiClient.convertToType(data['done_date'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('instance_id')) {
                obj['instance_id'] = ApiClient.convertToType(data['instance_id'], 'Number');
            }
            if (data.hasOwnProperty('item_order')) {
                obj['item_order'] = ApiClient.convertToType(data['item_order'], 'Number');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Date} done_date
    */
    done_date = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} instance_id
    */
    instance_id = undefined;
    /**
    * @member {Number} item_order
    */
    item_order = undefined;
    /**
    * @member {Boolean} required
    */
    required = undefined;








}


