/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Company model module.
* @module model/Company
* @version V1.0
*/
export default class Company {
    /**
    * Constructs a new <code>Company</code>.
    * @alias module:model/Company
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Company} obj Optional instance to populate.
    * @return {module:model/Company} The populated <code>Company</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Company();

            
            
            

            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} company_name
    */
    company_name = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;








}


