/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SimpleTag from './SimpleTag';





/**
* The ContactTag model module.
* @module model/ContactTag
* @version V1.0
*/
export default class ContactTag {
    /**
    * Constructs a new <code>ContactTag</code>.
    * @alias module:model/ContactTag
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ContactTag</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContactTag} obj Optional instance to populate.
    * @return {module:model/ContactTag} The populated <code>ContactTag</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactTag();

            
            
            

            if (data.hasOwnProperty('date_applied')) {
                obj['date_applied'] = ApiClient.convertToType(data['date_applied'], 'Date');
            }
            if (data.hasOwnProperty('tag')) {
                obj['tag'] = SimpleTag.constructFromObject(data['tag']);
            }
        }
        return obj;
    }

    /**
    * @member {Date} date_applied
    */
    date_applied = undefined;
    /**
    * @member {module:model/SimpleTag} tag
    */
    tag = undefined;








}


