/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CustomFieldOption from './CustomFieldOption';





/**
* The CustomFieldOption model module.
* @module model/CustomFieldOption
* @version V1.0
*/
export default class CustomFieldOption {
    /**
    * Constructs a new <code>CustomFieldOption</code>.
    * @alias module:model/CustomFieldOption
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CustomFieldOption</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CustomFieldOption} obj Optional instance to populate.
    * @return {module:model/CustomFieldOption} The populated <code>CustomFieldOption</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldOption();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [CustomFieldOption]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} label
    */
    label = undefined;
    /**
    * @member {Array.<module:model/CustomFieldOption>} options
    */
    options = undefined;








}


