/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CustomFieldValue model module.
* @module model/CustomFieldValue
* @version V1.0
*/
export default class CustomFieldValue {
    /**
    * Constructs a new <code>CustomFieldValue</code>.
    * @alias module:model/CustomFieldValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CustomFieldValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CustomFieldValue} obj Optional instance to populate.
    * @return {module:model/CustomFieldValue} The populated <code>CustomFieldValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldValue();

            
            
            

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Object} content
    */
    content = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;








}


