/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The EmailAddress model module.
* @module model/EmailAddress
* @version V1.0
*/
export default class EmailAddress {
    /**
    * Constructs a new <code>EmailAddress</code>.
    * @alias module:model/EmailAddress
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EmailAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmailAddress} obj Optional instance to populate.
    * @return {module:model/EmailAddress} The populated <code>EmailAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailAddress();

            
            
            

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {module:model/EmailAddress.FieldEnum} field
    */
    field = undefined;






    /**
    * Allowed values for the <code>field</code> property.
    * @enum {String}
    * @readonly
    */
    static FieldEnum = {
    
        /**
         * value: "EMAIL1"
         * @const
         */
        "EMAIL1": "EMAIL1",
    
        /**
         * value: "EMAIL2"
         * @const
         */
        "EMAIL2": "EMAIL2",
    
        /**
         * value: "EMAIL3"
         * @const
         */
        "EMAIL3": "EMAIL3"    
    };



}


