/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The FaxNumber model module.
* @module model/FaxNumber
* @version V1.0
*/
export default class FaxNumber {
    /**
    * Constructs a new <code>FaxNumber</code>.
    * @alias module:model/FaxNumber
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>FaxNumber</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FaxNumber} obj Optional instance to populate.
    * @return {module:model/FaxNumber} The populated <code>FaxNumber</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FaxNumber();

            
            
            

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/FaxNumber.FieldEnum} field
    */
    field = undefined;
    /**
    * @member {String} number
    */
    number = undefined;
    /**
    * @member {String} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>field</code> property.
    * @enum {String}
    * @readonly
    */
    static FieldEnum = {
    
        /**
         * value: "FAX1"
         * @const
         */
        "FAX1": "FAX1",
    
        /**
         * value: "FAX2"
         * @const
         */
        "FAX2": "FAX2"    
    };



}


