/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Item model module.
* @module model/Item
* @version V1.0
*/
export default class Item {
    /**
    * Constructs a new <code>Item</code>.
    * @alias module:model/Item
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Item} obj Optional instance to populate.
    * @return {module:model/Item} The populated <code>Item</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('next_item_id')) {
                obj['next_item_id'] = ApiClient.convertToType(data['next_item_id'], 'Number');
            }
            if (data.hasOwnProperty('previous_item_id')) {
                obj['previous_item_id'] = ApiClient.convertToType(data['previous_item_id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Number} next_item_id
    */
    next_item_id = undefined;
    /**
    * @member {Number} previous_item_id
    */
    previous_item_id = undefined;
    /**
    * @member {module:model/Item.TypeEnum} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "NULL"
         * @const
         */
        "NULL": "NULL",
    
        /**
         * value: "Start"
         * @const
         */
        "Start": "Start",
    
        /**
         * value: "Wait"
         * @const
         */
        "Wait": "Wait",
    
        /**
         * value: "DelayTimer"
         * @const
         */
        "DelayTimer": "DelayTimer",
    
        /**
         * value: "ContactTimer"
         * @const
         */
        "ContactTimer": "ContactTimer",
    
        /**
         * value: "DateTimer"
         * @const
         */
        "DateTimer": "DateTimer",
    
        /**
         * value: "Email"
         * @const
         */
        "Email": "Email",
    
        /**
         * value: "BardEmail"
         * @const
         */
        "BardEmail": "BardEmail",
    
        /**
         * value: "EmailConfirm"
         * @const
         */
        "EmailConfirm": "EmailConfirm",
    
        /**
         * value: "Voice"
         * @const
         */
        "Voice": "Voice",
    
        /**
         * value: "Fax"
         * @const
         */
        "Fax": "Fax",
    
        /**
         * value: "Letter"
         * @const
         */
        "Letter": "Letter",
    
        /**
         * value: "Tag"
         * @const
         */
        "Tag": "Tag",
    
        /**
         * value: "Opportunity"
         * @const
         */
        "Opportunity": "Opportunity",
    
        /**
         * value: "Note"
         * @const
         */
        "Note": "Note",
    
        /**
         * value: "Task"
         * @const
         */
        "Task": "Task",
    
        /**
         * value: "Appointment"
         * @const
         */
        "Appointment": "Appointment",
    
        /**
         * value: "AssignOwner"
         * @const
         */
        "AssignOwner": "AssignOwner",
    
        /**
         * value: "FieldValue"
         * @const
         */
        "FieldValue": "FieldValue",
    
        /**
         * value: "Fulfillment"
         * @const
         */
        "Fulfillment": "Fulfillment",
    
        /**
         * value: "Http"
         * @const
         */
        "Http": "Http",
    
        /**
         * value: "CustomerHub"
         * @const
         */
        "CustomerHub": "CustomerHub",
    
        /**
         * value: "ActionSet"
         * @const
         */
        "ActionSet": "ActionSet"    
    };



}


