/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The OpportunityContact model module.
* @module model/OpportunityContact
* @version V1.0
*/
export default class OpportunityContact {
    /**
    * Constructs a new <code>OpportunityContact</code>.
    * @alias module:model/OpportunityContact
    * @class
    * @param id {Number} 
    */

    constructor(id) {
        

        
        

        this['id'] = id;

        
    }

    /**
    * Constructs a <code>OpportunityContact</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OpportunityContact} obj Optional instance to populate.
    * @return {module:model/OpportunityContact} The populated <code>OpportunityContact</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpportunityContact();

            
            
            

            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('job_title')) {
                obj['job_title'] = ApiClient.convertToType(data['job_title'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} company_name
    */
    company_name = undefined;
    /**
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {String} first_name
    */
    first_name = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} job_title
    */
    job_title = undefined;
    /**
    * @member {String} last_name
    */
    last_name = undefined;
    /**
    * @member {String} phone_number
    */
    phone_number = undefined;








}


