/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import OrderContactDetails from './OrderContactDetails';
import OrderItem from './OrderItem';
import ShippingInformation from './ShippingInformation';





/**
* The Order model module.
* @module model/Order
* @version V1.0
*/
export default class Order {
    /**
    * Constructs a new <code>Order</code>.
    * @alias module:model/Order
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Order} obj Optional instance to populate.
    * @return {module:model/Order} The populated <code>Order</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            
            
            

            if (data.hasOwnProperty('contact')) {
                obj['contact'] = OrderContactDetails.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lead_affiliate_id')) {
                obj['lead_affiliate_id'] = ApiClient.convertToType(data['lead_affiliate_id'], 'Number');
            }
            if (data.hasOwnProperty('modification_date')) {
                obj['modification_date'] = ApiClient.convertToType(data['modification_date'], 'String');
            }
            if (data.hasOwnProperty('order_date')) {
                obj['order_date'] = ApiClient.convertToType(data['order_date'], 'String');
            }
            if (data.hasOwnProperty('order_items')) {
                obj['order_items'] = ApiClient.convertToType(data['order_items'], [OrderItem]);
            }
            if (data.hasOwnProperty('recurring')) {
                obj['recurring'] = ApiClient.convertToType(data['recurring'], 'Boolean');
            }
            if (data.hasOwnProperty('refund_total')) {
                obj['refund_total'] = ApiClient.convertToType(data['refund_total'], 'Number');
            }
            if (data.hasOwnProperty('sales_affiliate_id')) {
                obj['sales_affiliate_id'] = ApiClient.convertToType(data['sales_affiliate_id'], 'Number');
            }
            if (data.hasOwnProperty('shipping_information')) {
                obj['shipping_information'] = ShippingInformation.constructFromObject(data['shipping_information']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('total_due')) {
                obj['total_due'] = ApiClient.convertToType(data['total_due'], 'Number');
            }
            if (data.hasOwnProperty('total_paid')) {
                obj['total_paid'] = ApiClient.convertToType(data['total_paid'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/OrderContactDetails} contact
    */
    contact = undefined;
    /**
    * @member {String} creation_date
    */
    creation_date = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} lead_affiliate_id
    */
    lead_affiliate_id = undefined;
    /**
    * @member {String} modification_date
    */
    modification_date = undefined;
    /**
    * @member {String} order_date
    */
    order_date = undefined;
    /**
    * @member {Array.<module:model/OrderItem>} order_items
    */
    order_items = undefined;
    /**
    * @member {Boolean} recurring
    */
    recurring = undefined;
    /**
    * @member {Number} refund_total
    */
    refund_total = undefined;
    /**
    * @member {Number} sales_affiliate_id
    */
    sales_affiliate_id = undefined;
    /**
    * @member {module:model/ShippingInformation} shipping_information
    */
    shipping_information = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {Number} total
    */
    total = undefined;
    /**
    * @member {Number} total_due
    */
    total_due = undefined;
    /**
    * @member {Number} total_paid
    */
    total_paid = undefined;








}


