/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PhoneNumber model module.
* @module model/PhoneNumber
* @version V1.0
*/
export default class PhoneNumber {
    /**
    * Constructs a new <code>PhoneNumber</code>.
    * @alias module:model/PhoneNumber
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PhoneNumber</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PhoneNumber} obj Optional instance to populate.
    * @return {module:model/PhoneNumber} The populated <code>PhoneNumber</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PhoneNumber();

            
            
            

            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} extension
    */
    extension = undefined;
    /**
    * @member {module:model/PhoneNumber.FieldEnum} field
    */
    field = undefined;
    /**
    * @member {String} number
    */
    number = undefined;
    /**
    * @member {String} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>field</code> property.
    * @enum {String}
    * @readonly
    */
    static FieldEnum = {
    
        /**
         * value: "PHONE1"
         * @const
         */
        "PHONE1": "PHONE1",
    
        /**
         * value: "PHONE2"
         * @const
         */
        "PHONE2": "PHONE2",
    
        /**
         * value: "PHONE3"
         * @const
         */
        "PHONE3": "PHONE3",
    
        /**
         * value: "PHONE4"
         * @const
         */
        "PHONE4": "PHONE4",
    
        /**
         * value: "PHONE5"
         * @const
         */
        "PHONE5": "PHONE5"    
    };



}


