/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Product from './Product';





/**
* The ProductList model module.
* @module model/ProductList
* @version V1.0
*/
export default class ProductList {
    /**
    * Constructs a new <code>ProductList</code>.
    * @alias module:model/ProductList
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProductList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProductList} obj Optional instance to populate.
    * @return {module:model/ProductList} The populated <code>ProductList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductList();

            
            
            

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [Product]);
            }
            if (data.hasOwnProperty('sync_token')) {
                obj['sync_token'] = ApiClient.convertToType(data['sync_token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} count
    */
    count = undefined;
    /**
    * @member {String} next
    */
    next = undefined;
    /**
    * @member {String} previous
    */
    previous = undefined;
    /**
    * @member {Array.<module:model/Product>} products
    */
    products = undefined;
    /**
    * @member {String} sync_token
    */
    sync_token = undefined;








}


