/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ProductOptionValue model module.
* @module model/ProductOptionValue
* @version V1.0
*/
export default class ProductOptionValue {
    /**
    * Constructs a new <code>ProductOptionValue</code>.
    * @alias module:model/ProductOptionValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ProductOptionValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProductOptionValue} obj Optional instance to populate.
    * @return {module:model/ProductOptionValue} The populated <code>ProductOptionValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductOptionValue();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('is_default')) {
                obj['is_default'] = ApiClient.convertToType(data['is_default'], 'Boolean');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('price_adjustment')) {
                obj['price_adjustment'] = ApiClient.convertToType(data['price_adjustment'], 'Number');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} index
    */
    index = undefined;
    /**
    * @member {Boolean} is_default
    */
    is_default = undefined;
    /**
    * @member {String} label
    */
    label = undefined;
    /**
    * @member {Number} price_adjustment
    */
    price_adjustment = undefined;
    /**
    * @member {String} sku
    */
    sku = undefined;








}


