/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProductOption from './ProductOption';
import SubscriptionPlan from './SubscriptionPlan';





/**
* The Product model module.
* @module model/Product
* @version V1.0
*/
export default class Product {
    /**
    * Constructs a new <code>Product</code>.
    * @alias module:model/Product
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Product} obj Optional instance to populate.
    * @return {module:model/Product} The populated <code>Product</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Product();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('product_desc')) {
                obj['product_desc'] = ApiClient.convertToType(data['product_desc'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('product_options')) {
                obj['product_options'] = ApiClient.convertToType(data['product_options'], [ProductOption]);
            }
            if (data.hasOwnProperty('product_price')) {
                obj['product_price'] = ApiClient.convertToType(data['product_price'], 'Number');
            }
            if (data.hasOwnProperty('product_short_desc')) {
                obj['product_short_desc'] = ApiClient.convertToType(data['product_short_desc'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('sub_category_id')) {
                obj['sub_category_id'] = ApiClient.convertToType(data['sub_category_id'], 'Number');
            }
            if (data.hasOwnProperty('subscription_only')) {
                obj['subscription_only'] = ApiClient.convertToType(data['subscription_only'], 'Boolean');
            }
            if (data.hasOwnProperty('subscription_plans')) {
                obj['subscription_plans'] = ApiClient.convertToType(data['subscription_plans'], [SubscriptionPlan]);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} product_desc
    */
    product_desc = undefined;
    /**
    * @member {String} product_name
    */
    product_name = undefined;
    /**
    * @member {Array.<module:model/ProductOption>} product_options
    */
    product_options = undefined;
    /**
    * @member {Number} product_price
    */
    product_price = undefined;
    /**
    * @member {String} product_short_desc
    */
    product_short_desc = undefined;
    /**
    * @member {String} sku
    */
    sku = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {Number} sub_category_id
    */
    sub_category_id = undefined;
    /**
    * @member {Boolean} subscription_only
    */
    subscription_only = undefined;
    /**
    * @member {Array.<module:model/SubscriptionPlan>} subscription_plans
    */
    subscription_plans = undefined;
    /**
    * @member {String} url
    */
    url = undefined;








}


