/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Relationship model module.
* @module model/Relationship
* @version V1.0
*/
export default class Relationship {
    /**
    * Constructs a new <code>Relationship</code>.
    * @alias module:model/Relationship
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Relationship</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Relationship} obj Optional instance to populate.
    * @return {module:model/Relationship} The populated <code>Relationship</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Relationship();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('linked_contact_id')) {
                obj['linked_contact_id'] = ApiClient.convertToType(data['linked_contact_id'], 'Number');
            }
            if (data.hasOwnProperty('relationship_type_id')) {
                obj['relationship_type_id'] = ApiClient.convertToType(data['relationship_type_id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} linked_contact_id
    */
    linked_contact_id = undefined;
    /**
    * @member {Number} relationship_type_id
    */
    relationship_type_id = undefined;








}


