/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RestHook model module.
* @module model/RestHook
* @version V1.0
*/
export default class RestHook {
    /**
    * Constructs a new <code>RestHook</code>.
    * @alias module:model/RestHook
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RestHook</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RestHook} obj Optional instance to populate.
    * @return {module:model/RestHook} The populated <code>RestHook</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestHook();

            
            
            

            if (data.hasOwnProperty('eventKey')) {
                obj['eventKey'] = ApiClient.convertToType(data['eventKey'], 'String');
            }
            if (data.hasOwnProperty('hookUrl')) {
                obj['hookUrl'] = ApiClient.convertToType(data['hookUrl'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} eventKey
    */
    eventKey = undefined;
    /**
    * @member {String} hookUrl
    */
    hookUrl = undefined;
    /**
    * @member {String} key
    */
    key = undefined;
    /**
    * @member {module:model/RestHook.StatusEnum} status
    */
    status = undefined;






    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
    
        /**
         * value: "Unverified"
         * @const
         */
        "Unverified": "Unverified",
    
        /**
         * value: "Verified"
         * @const
         */
        "Verified": "Verified",
    
        /**
         * value: "Inactive"
         * @const
         */
        "Inactive": "Inactive"    
    };



}


