/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SalesPipeline model module.
* @module model/SalesPipeline
* @version V1.0
*/
export default class SalesPipeline {
    /**
    * Constructs a new <code>SalesPipeline</code>.
    * @alias module:model/SalesPipeline
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SalesPipeline</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SalesPipeline} obj Optional instance to populate.
    * @return {module:model/SalesPipeline} The populated <code>SalesPipeline</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SalesPipeline();

            
            
            

            if (data.hasOwnProperty('end_stage')) {
                obj['end_stage'] = ApiClient.convertToType(data['end_stage'], 'Boolean');
            }
            if (data.hasOwnProperty('is_default')) {
                obj['is_default'] = ApiClient.convertToType(data['is_default'], 'Boolean');
            }
            if (data.hasOwnProperty('stage_count')) {
                obj['stage_count'] = ApiClient.convertToType(data['stage_count'], 'Number');
            }
            if (data.hasOwnProperty('stage_id')) {
                obj['stage_id'] = ApiClient.convertToType(data['stage_id'], 'Number');
            }
            if (data.hasOwnProperty('stage_name')) {
                obj['stage_name'] = ApiClient.convertToType(data['stage_name'], 'String');
            }
            if (data.hasOwnProperty('stage_order')) {
                obj['stage_order'] = ApiClient.convertToType(data['stage_order'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} end_stage
    */
    end_stage = undefined;
    /**
    * @member {Boolean} is_default
    */
    is_default = undefined;
    /**
    * @member {Number} stage_count
    */
    stage_count = undefined;
    /**
    * @member {Number} stage_id
    */
    stage_id = undefined;
    /**
    * @member {String} stage_name
    */
    stage_name = undefined;
    /**
    * @member {Number} stage_order
    */
    stage_order = undefined;








}


