/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HistoricalCounts from './HistoricalCounts';
import SequencePath from './SequencePath';





/**
* The Sequence model module.
* @module model/Sequence
* @version V1.0
*/
export default class Sequence {
    /**
    * Constructs a new <code>Sequence</code>.
    * @alias module:model/Sequence
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Sequence</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Sequence} obj Optional instance to populate.
    * @return {module:model/Sequence} The populated <code>Sequence</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sequence();

            
            
            

            if (data.hasOwnProperty('active_contact_count')) {
                obj['active_contact_count'] = ApiClient.convertToType(data['active_contact_count'], 'Number');
            }
            if (data.hasOwnProperty('active_contact_count_completed')) {
                obj['active_contact_count_completed'] = ApiClient.convertToType(data['active_contact_count_completed'], 'Number');
            }
            if (data.hasOwnProperty('historical_contact_count')) {
                obj['historical_contact_count'] = HistoricalCounts.constructFromObject(data['historical_contact_count']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('paths')) {
                obj['paths'] = ApiClient.convertToType(data['paths'], [SequencePath]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} active_contact_count
    */
    active_contact_count = undefined;
    /**
    * @member {Number} active_contact_count_completed
    */
    active_contact_count_completed = undefined;
    /**
    * @member {module:model/HistoricalCounts} historical_contact_count
    */
    historical_contact_count = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<module:model/SequencePath>} paths
    */
    paths = undefined;








}


