/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SetOfIds model module.
* @module model/SetOfIds
* @version V1.0
*/
export default class SetOfIds {
    /**
    * Constructs a new <code>SetOfIds</code>.
    * @alias module:model/SetOfIds
    * @class
    * @param ids {Array.<Number>} 
    */

    constructor(ids) {
        

        
        

        this['ids'] = ids;

        
    }

    /**
    * Constructs a <code>SetOfIds</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SetOfIds} obj Optional instance to populate.
    * @return {module:model/SetOfIds} The populated <code>SetOfIds</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetOfIds();

            
            
            

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<Number>} ids
    */
    ids = undefined;








}


