/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import StageDetails from './StageDetails';





/**
* The SimpleOpportunityStage model module.
* @module model/SimpleOpportunityStage
* @version V1.0
*/
export default class SimpleOpportunityStage {
    /**
    * Constructs a new <code>SimpleOpportunityStage</code>.
    * @alias module:model/SimpleOpportunityStage
    * @class
    * @param id {Number} 
    */

    constructor(id) {
        

        
        

        this['id'] = id;

        
    }

    /**
    * Constructs a <code>SimpleOpportunityStage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SimpleOpportunityStage} obj Optional instance to populate.
    * @return {module:model/SimpleOpportunityStage} The populated <code>SimpleOpportunityStage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleOpportunityStage();

            
            
            

            if (data.hasOwnProperty('details')) {
                obj['details'] = StageDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('reasons')) {
                obj['reasons'] = ApiClient.convertToType(data['reasons'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/StageDetails} details
    */
    details = undefined;
    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<String>} reasons
    */
    reasons = undefined;








}


