/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CheckListItemDetails from './CheckListItemDetails';





/**
* The StageDetails model module.
* @module model/StageDetails
* @version V1.0
*/
export default class StageDetails {
    /**
    * Constructs a new <code>StageDetails</code>.
    * @alias module:model/StageDetails
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>StageDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StageDetails} obj Optional instance to populate.
    * @return {module:model/StageDetails} The populated <code>StageDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StageDetails();

            
            
            

            if (data.hasOwnProperty('check_list_items')) {
                obj['check_list_items'] = ApiClient.convertToType(data['check_list_items'], [CheckListItemDetails]);
            }
            if (data.hasOwnProperty('probability')) {
                obj['probability'] = ApiClient.convertToType(data['probability'], 'Number');
            }
            if (data.hasOwnProperty('stage_order')) {
                obj['stage_order'] = ApiClient.convertToType(data['stage_order'], 'Number');
            }
            if (data.hasOwnProperty('target_num_days')) {
                obj['target_num_days'] = ApiClient.convertToType(data['target_num_days'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/CheckListItemDetails>} check_list_items
    */
    check_list_items = undefined;
    /**
    * @member {Number} probability
    */
    probability = undefined;
    /**
    * @member {Number} stage_order
    */
    stage_order = undefined;
    /**
    * @member {Number} target_num_days
    */
    target_num_days = undefined;








}


