/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TagId model module.
* @module model/TagId
* @version V1.0
*/
export default class TagId {
    /**
    * Constructs a new <code>TagId</code>.
    * @alias module:model/TagId
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TagId</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TagId} obj Optional instance to populate.
    * @return {module:model/TagId} The populated <code>TagId</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TagId();

            
            
            

            if (data.hasOwnProperty('tagIds')) {
                obj['tagIds'] = ApiClient.convertToType(data['tagIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<Number>} tagIds
    */
    tagIds = undefined;








}


