/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Address from './Address';
import Company from './Company';
import CustomFieldValue from './CustomFieldValue';
import EmailAddress from './EmailAddress';
import FaxNumber from './FaxNumber';
import PhoneNumber from './PhoneNumber';
import Relationship from './Relationship';





/**
* The UpsertContact model module.
* @module model/UpsertContact
* @version V1.0
*/
export default class UpsertContact {
    /**
    * Constructs a new <code>UpsertContact</code>.
    * @alias module:model/UpsertContact
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>UpsertContact</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpsertContact} obj Optional instance to populate.
    * @return {module:model/UpsertContact} The populated <code>UpsertContact</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpsertContact();

            
            
            

            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], [Address]);
            }
            if (data.hasOwnProperty('birthday')) {
                obj['birthday'] = ApiClient.convertToType(data['birthday'], 'Date');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = Company.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('contact_type')) {
                obj['contact_type'] = ApiClient.convertToType(data['contact_type'], 'String');
            }
            if (data.hasOwnProperty('custom_fields')) {
                obj['custom_fields'] = ApiClient.convertToType(data['custom_fields'], [CustomFieldValue]);
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('duplicate_option')) {
                obj['duplicate_option'] = ApiClient.convertToType(data['duplicate_option'], 'String');
            }
            if (data.hasOwnProperty('email_addresses')) {
                obj['email_addresses'] = ApiClient.convertToType(data['email_addresses'], [EmailAddress]);
            }
            if (data.hasOwnProperty('family_name')) {
                obj['family_name'] = ApiClient.convertToType(data['family_name'], 'String');
            }
            if (data.hasOwnProperty('fax_numbers')) {
                obj['fax_numbers'] = ApiClient.convertToType(data['fax_numbers'], [FaxNumber]);
            }
            if (data.hasOwnProperty('given_name')) {
                obj['given_name'] = ApiClient.convertToType(data['given_name'], 'String');
            }
            if (data.hasOwnProperty('job_title')) {
                obj['job_title'] = ApiClient.convertToType(data['job_title'], 'String');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('lead_source_id')) {
                obj['lead_source_id'] = ApiClient.convertToType(data['lead_source_id'], 'Number');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('opt_in_reason')) {
                obj['opt_in_reason'] = ApiClient.convertToType(data['opt_in_reason'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
            }
            if (data.hasOwnProperty('phone_numbers')) {
                obj['phone_numbers'] = ApiClient.convertToType(data['phone_numbers'], [PhoneNumber]);
            }
            if (data.hasOwnProperty('preferred_locale')) {
                obj['preferred_locale'] = ApiClient.convertToType(data['preferred_locale'], 'String');
            }
            if (data.hasOwnProperty('preferred_name')) {
                obj['preferred_name'] = ApiClient.convertToType(data['preferred_name'], 'String');
            }
            if (data.hasOwnProperty('prefix')) {
                obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = ApiClient.convertToType(data['relationships'], [Relationship]);
            }
            if (data.hasOwnProperty('source_type')) {
                obj['source_type'] = ApiClient.convertToType(data['source_type'], 'String');
            }
            if (data.hasOwnProperty('suffix')) {
                obj['suffix'] = ApiClient.convertToType(data['suffix'], 'String');
            }
            if (data.hasOwnProperty('tag_ids')) {
                obj['tag_ids'] = ApiClient.convertToType(data['tag_ids'], ['Number']);
            }
            if (data.hasOwnProperty('time_zone')) {
                obj['time_zone'] = ApiClient.convertToType(data['time_zone'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Address>} addresses
    */
    addresses = undefined;
    /**
    * @member {Date} birthday
    */
    birthday = undefined;
    /**
    * @member {module:model/Company} company
    */
    company = undefined;
    /**
    * @member {String} contact_type
    */
    contact_type = undefined;
    /**
    * @member {Array.<module:model/CustomFieldValue>} custom_fields
    */
    custom_fields = undefined;
    /**
    * @member {Date} date_created
    */
    date_created = undefined;
    /**
    * @member {module:model/UpsertContact.DuplicateOptionEnum} duplicate_option
    */
    duplicate_option = undefined;
    /**
    * @member {Array.<module:model/EmailAddress>} email_addresses
    */
    email_addresses = undefined;
    /**
    * @member {String} family_name
    */
    family_name = undefined;
    /**
    * @member {Array.<module:model/FaxNumber>} fax_numbers
    */
    fax_numbers = undefined;
    /**
    * @member {String} given_name
    */
    given_name = undefined;
    /**
    * @member {String} job_title
    */
    job_title = undefined;
    /**
    * @member {Date} last_updated
    */
    last_updated = undefined;
    /**
    * @member {Number} lead_source_id
    */
    lead_source_id = undefined;
    /**
    * @member {String} middle_name
    */
    middle_name = undefined;
    /**
    * @member {String} notes
    */
    notes = undefined;
    /**
    * @member {String} opt_in_reason
    */
    opt_in_reason = undefined;
    /**
    * @member {Number} owner_id
    */
    owner_id = undefined;
    /**
    * @member {Array.<module:model/PhoneNumber>} phone_numbers
    */
    phone_numbers = undefined;
    /**
    * @member {String} preferred_locale
    */
    preferred_locale = undefined;
    /**
    * @member {String} preferred_name
    */
    preferred_name = undefined;
    /**
    * @member {String} prefix
    */
    prefix = undefined;
    /**
    * @member {Array.<module:model/Relationship>} relationships
    */
    relationships = undefined;
    /**
    * @member {module:model/UpsertContact.SourceTypeEnum} source_type
    */
    source_type = undefined;
    /**
    * @member {String} suffix
    */
    suffix = undefined;
    /**
    * @member {Array.<Number>} tag_ids
    */
    tag_ids = undefined;
    /**
    * @member {String} time_zone
    */
    time_zone = undefined;
    /**
    * @member {String} website
    */
    website = undefined;






    /**
    * Allowed values for the <code>duplicate_option</code> property.
    * @enum {String}
    * @readonly
    */
    static DuplicateOptionEnum = {
    
        /**
         * value: "Email"
         * @const
         */
        "Email": "Email",
    
        /**
         * value: "EmailAndName"
         * @const
         */
        "EmailAndName": "EmailAndName"    
    };

    /**
    * Allowed values for the <code>source_type</code> property.
    * @enum {String}
    * @readonly
    */
    static SourceTypeEnum = {
    
        /**
         * value: "WEBFORM"
         * @const
         */
        "WEBFORM": "WEBFORM",
    
        /**
         * value: "LANDINGPAGE"
         * @const
         */
        "LANDINGPAGE": "LANDINGPAGE",
    
        /**
         * value: "IMPORT"
         * @const
         */
        "IMPORT": "IMPORT",
    
        /**
         * value: "MANUAL"
         * @const
         */
        "MANUAL": "MANUAL",
    
        /**
         * value: "API"
         * @const
         */
        "API": "API",
    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER": "OTHER",
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN": "UNKNOWN"    
    };



}


