/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.Campaign();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Campaign', function() {
    it('should create an instance of Campaign', function() {
      // uncomment below and update the code to test Campaign
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be.a(InfusionsoftRestApi.Campaign);
    });

    it('should have the property activeContactCount (base name: "active_contact_count")', function() {
      // uncomment below and update the code to test the property activeContactCount
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property completedContactCount (base name: "completed_contact_count")', function() {
      // uncomment below and update the code to test the property completedContactCount
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "error_message")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property goals (base name: "goals")', function() {
      // uncomment below and update the code to test the property goals
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property publishedDate (base name: "published_date")', function() {
      // uncomment below and update the code to test the property publishedDate
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property publishedStatus (base name: "published_status")', function() {
      // uncomment below and update the code to test the property publishedStatus
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property publishedTimeZone (base name: "published_time_zone")', function() {
      // uncomment below and update the code to test the property publishedTimeZone
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property sequences (base name: "sequences")', function() {
      // uncomment below and update the code to test the property sequences
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

    it('should have the property timeZone (base name: "time_zone")', function() {
      // uncomment below and update the code to test the property timeZone
      //var instane = new InfusionsoftRestApi.Campaign();
      //expect(instance).to.be();
    });

  });

}));
