/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.Order();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Order', function() {
    it('should create an instance of Order', function() {
      // uncomment below and update the code to test Order
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be.a(InfusionsoftRestApi.Order);
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property leadAffiliateId (base name: "lead_affiliate_id")', function() {
      // uncomment below and update the code to test the property leadAffiliateId
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property modificationDate (base name: "modification_date")', function() {
      // uncomment below and update the code to test the property modificationDate
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property orderDate (base name: "order_date")', function() {
      // uncomment below and update the code to test the property orderDate
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property orderItems (base name: "order_items")', function() {
      // uncomment below and update the code to test the property orderItems
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property recurring (base name: "recurring")', function() {
      // uncomment below and update the code to test the property recurring
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property refundTotal (base name: "refund_total")', function() {
      // uncomment below and update the code to test the property refundTotal
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property salesAffiliateId (base name: "sales_affiliate_id")', function() {
      // uncomment below and update the code to test the property salesAffiliateId
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property shippingInformation (base name: "shipping_information")', function() {
      // uncomment below and update the code to test the property shippingInformation
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property totalDue (base name: "total_due")', function() {
      // uncomment below and update the code to test the property totalDue
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

    it('should have the property totalPaid (base name: "total_paid")', function() {
      // uncomment below and update the code to test the property totalPaid
      //var instane = new InfusionsoftRestApi.Order();
      //expect(instance).to.be();
    });

  });

}));
