/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.ProductOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductOption', function() {
    it('should create an instance of ProductOption', function() {
      // uncomment below and update the code to test ProductOption
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be.a(InfusionsoftRestApi.ProductOption);
    });

    it('should have the property allowSpaces (base name: "allow_spaces")', function() {
      // uncomment below and update the code to test the property allowSpaces
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canContainCharacter (base name: "can_contain_character")', function() {
      // uncomment below and update the code to test the property canContainCharacter
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canContainNumber (base name: "can_contain_number")', function() {
      // uncomment below and update the code to test the property canContainNumber
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canEndWithCharacter (base name: "can_end_with_character")', function() {
      // uncomment below and update the code to test the property canEndWithCharacter
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canEndWithNumber (base name: "can_end_with_number")', function() {
      // uncomment below and update the code to test the property canEndWithNumber
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canStartWithCharacter (base name: "can_start_with_character")', function() {
      // uncomment below and update the code to test the property canStartWithCharacter
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property canStartWithNumber (base name: "can_start_with_number")', function() {
      // uncomment below and update the code to test the property canStartWithNumber
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property displayIndex (base name: "display_index")', function() {
      // uncomment below and update the code to test the property displayIndex
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property maxChars (base name: "max_chars")', function() {
      // uncomment below and update the code to test the property maxChars
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property minChars (base name: "min_chars")', function() {
      // uncomment below and update the code to test the property minChars
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property required (base name: "required")', function() {
      // uncomment below and update the code to test the property required
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property textMessage (base name: "text_message")', function() {
      // uncomment below and update the code to test the property textMessage
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instane = new InfusionsoftRestApi.ProductOption();
      //expect(instance).to.be();
    });

  });

}));
