/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.Relationship();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Relationship', function() {
    it('should create an instance of Relationship', function() {
      // uncomment below and update the code to test Relationship
      //var instane = new InfusionsoftRestApi.Relationship();
      //expect(instance).to.be.a(InfusionsoftRestApi.Relationship);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new InfusionsoftRestApi.Relationship();
      //expect(instance).to.be();
    });

    it('should have the property linkedContactId (base name: "linked_contact_id")', function() {
      // uncomment below and update the code to test the property linkedContactId
      //var instane = new InfusionsoftRestApi.Relationship();
      //expect(instance).to.be();
    });

    it('should have the property relationshipTypeId (base name: "relationship_type_id")', function() {
      // uncomment below and update the code to test the property relationshipTypeId
      //var instane = new InfusionsoftRestApi.Relationship();
      //expect(instance).to.be();
    });

  });

}));
