/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.SalesPipeline();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SalesPipeline', function() {
    it('should create an instance of SalesPipeline', function() {
      // uncomment below and update the code to test SalesPipeline
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be.a(InfusionsoftRestApi.SalesPipeline);
    });

    it('should have the property endStage (base name: "end_stage")', function() {
      // uncomment below and update the code to test the property endStage
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

    it('should have the property isDefault (base name: "is_default")', function() {
      // uncomment below and update the code to test the property isDefault
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

    it('should have the property stageCount (base name: "stage_count")', function() {
      // uncomment below and update the code to test the property stageCount
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

    it('should have the property stageId (base name: "stage_id")', function() {
      // uncomment below and update the code to test the property stageId
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

    it('should have the property stageName (base name: "stage_name")', function() {
      // uncomment below and update the code to test the property stageName
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

    it('should have the property stageOrder (base name: "stage_order")', function() {
      // uncomment below and update the code to test the property stageOrder
      //var instane = new InfusionsoftRestApi.SalesPipeline();
      //expect(instance).to.be();
    });

  });

}));
