/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Address from './model/Address';
import Appointment from './model/Appointment';
import AppointmentList from './model/AppointmentList';
import AppointmentStatus from './model/AppointmentStatus';
import AppointmentStatusList from './model/AppointmentStatusList';
import BasicContact from './model/BasicContact';
import Campaign from './model/Campaign';
import CampaignList from './model/CampaignList';
import CheckListItemDetails from './model/CheckListItemDetails';
import Company from './model/Company';
import ContactList from './model/ContactList';
import ContactTag from './model/ContactTag';
import ContactTagList from './model/ContactTagList';
import CustomFieldMetaData from './model/CustomFieldMetaData';
import CustomFieldOption from './model/CustomFieldOption';
import CustomFieldValue from './model/CustomFieldValue';
import EmailAddress from './model/EmailAddress';
import Entrylongstring from './model/Entrylongstring';
import FaxNumber from './model/FaxNumber';
import FullContact from './model/FullContact';
import Goal from './model/Goal';
import HistoricalCounts from './model/HistoricalCounts';
import Item from './model/Item';
import Opportunity from './model/Opportunity';
import OpportunityContact from './model/OpportunityContact';
import OpportunityList from './model/OpportunityList';
import Order from './model/Order';
import OrderContactDetails from './model/OrderContactDetails';
import OrderItem from './model/OrderItem';
import OrderList from './model/OrderList';
import PhoneNumber from './model/PhoneNumber';
import Product from './model/Product';
import ProductList from './model/ProductList';
import ProductOption from './model/ProductOption';
import ProductOptionValue from './model/ProductOptionValue';
import ProductStatus from './model/ProductStatus';
import ProductStatusList from './model/ProductStatusList';
import Relationship from './model/Relationship';
import RestHook from './model/RestHook';
import RestHookRequest from './model/RestHookRequest';
import SalesPipeline from './model/SalesPipeline';
import Sequence from './model/Sequence';
import SequencePath from './model/SequencePath';
import SetOfIds from './model/SetOfIds';
import ShippingInformation from './model/ShippingInformation';
import SimpleOpportunityStage from './model/SimpleOpportunityStage';
import SimpleProduct from './model/SimpleProduct';
import SimpleTag from './model/SimpleTag';
import SimpleUser from './model/SimpleUser';
import StageDetails from './model/StageDetails';
import SubscriptionPlan from './model/SubscriptionPlan';
import TagId from './model/TagId';
import Task from './model/Task';
import TaskList from './model/TaskList';
import TaskStatus from './model/TaskStatus';
import TaskStatusList from './model/TaskStatusList';
import Transaction from './model/Transaction';
import TransactionList from './model/TransactionList';
import UpsertContact from './model/UpsertContact';
import AppointmentApi from './api/AppointmentApi';
import CampaignApi from './api/CampaignApi';
import ContactApi from './api/ContactApi';
import ECommerceApi from './api/ECommerceApi';
import OpportunityApi from './api/OpportunityApi';
import ProductApi from './api/ProductApi';
import RESTHooksApi from './api/RESTHooksApi';
import TaskApi from './api/TaskApi';


/**
* ERROR_UNKNOWN.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var InfusionsoftRestApi = require('index'); // See note below*.
* var xxxSvc = new InfusionsoftRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new InfusionsoftRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new InfusionsoftRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new InfusionsoftRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version V1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The Appointment model constructor.
     * @property {module:model/Appointment}
     */
    Appointment,

    /**
     * The AppointmentList model constructor.
     * @property {module:model/AppointmentList}
     */
    AppointmentList,

    /**
     * The AppointmentStatus model constructor.
     * @property {module:model/AppointmentStatus}
     */
    AppointmentStatus,

    /**
     * The AppointmentStatusList model constructor.
     * @property {module:model/AppointmentStatusList}
     */
    AppointmentStatusList,

    /**
     * The BasicContact model constructor.
     * @property {module:model/BasicContact}
     */
    BasicContact,

    /**
     * The Campaign model constructor.
     * @property {module:model/Campaign}
     */
    Campaign,

    /**
     * The CampaignList model constructor.
     * @property {module:model/CampaignList}
     */
    CampaignList,

    /**
     * The CheckListItemDetails model constructor.
     * @property {module:model/CheckListItemDetails}
     */
    CheckListItemDetails,

    /**
     * The Company model constructor.
     * @property {module:model/Company}
     */
    Company,

    /**
     * The ContactList model constructor.
     * @property {module:model/ContactList}
     */
    ContactList,

    /**
     * The ContactTag model constructor.
     * @property {module:model/ContactTag}
     */
    ContactTag,

    /**
     * The ContactTagList model constructor.
     * @property {module:model/ContactTagList}
     */
    ContactTagList,

    /**
     * The CustomFieldMetaData model constructor.
     * @property {module:model/CustomFieldMetaData}
     */
    CustomFieldMetaData,

    /**
     * The CustomFieldOption model constructor.
     * @property {module:model/CustomFieldOption}
     */
    CustomFieldOption,

    /**
     * The CustomFieldValue model constructor.
     * @property {module:model/CustomFieldValue}
     */
    CustomFieldValue,

    /**
     * The EmailAddress model constructor.
     * @property {module:model/EmailAddress}
     */
    EmailAddress,

    /**
     * The Entrylongstring model constructor.
     * @property {module:model/Entrylongstring}
     */
    Entrylongstring,

    /**
     * The FaxNumber model constructor.
     * @property {module:model/FaxNumber}
     */
    FaxNumber,

    /**
     * The FullContact model constructor.
     * @property {module:model/FullContact}
     */
    FullContact,

    /**
     * The Goal model constructor.
     * @property {module:model/Goal}
     */
    Goal,

    /**
     * The HistoricalCounts model constructor.
     * @property {module:model/HistoricalCounts}
     */
    HistoricalCounts,

    /**
     * The Item model constructor.
     * @property {module:model/Item}
     */
    Item,

    /**
     * The Opportunity model constructor.
     * @property {module:model/Opportunity}
     */
    Opportunity,

    /**
     * The OpportunityContact model constructor.
     * @property {module:model/OpportunityContact}
     */
    OpportunityContact,

    /**
     * The OpportunityList model constructor.
     * @property {module:model/OpportunityList}
     */
    OpportunityList,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OrderContactDetails model constructor.
     * @property {module:model/OrderContactDetails}
     */
    OrderContactDetails,

    /**
     * The OrderItem model constructor.
     * @property {module:model/OrderItem}
     */
    OrderItem,

    /**
     * The OrderList model constructor.
     * @property {module:model/OrderList}
     */
    OrderList,

    /**
     * The PhoneNumber model constructor.
     * @property {module:model/PhoneNumber}
     */
    PhoneNumber,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductList model constructor.
     * @property {module:model/ProductList}
     */
    ProductList,

    /**
     * The ProductOption model constructor.
     * @property {module:model/ProductOption}
     */
    ProductOption,

    /**
     * The ProductOptionValue model constructor.
     * @property {module:model/ProductOptionValue}
     */
    ProductOptionValue,

    /**
     * The ProductStatus model constructor.
     * @property {module:model/ProductStatus}
     */
    ProductStatus,

    /**
     * The ProductStatusList model constructor.
     * @property {module:model/ProductStatusList}
     */
    ProductStatusList,

    /**
     * The Relationship model constructor.
     * @property {module:model/Relationship}
     */
    Relationship,

    /**
     * The RestHook model constructor.
     * @property {module:model/RestHook}
     */
    RestHook,

    /**
     * The RestHookRequest model constructor.
     * @property {module:model/RestHookRequest}
     */
    RestHookRequest,

    /**
     * The SalesPipeline model constructor.
     * @property {module:model/SalesPipeline}
     */
    SalesPipeline,

    /**
     * The Sequence model constructor.
     * @property {module:model/Sequence}
     */
    Sequence,

    /**
     * The SequencePath model constructor.
     * @property {module:model/SequencePath}
     */
    SequencePath,

    /**
     * The SetOfIds model constructor.
     * @property {module:model/SetOfIds}
     */
    SetOfIds,

    /**
     * The ShippingInformation model constructor.
     * @property {module:model/ShippingInformation}
     */
    ShippingInformation,

    /**
     * The SimpleOpportunityStage model constructor.
     * @property {module:model/SimpleOpportunityStage}
     */
    SimpleOpportunityStage,

    /**
     * The SimpleProduct model constructor.
     * @property {module:model/SimpleProduct}
     */
    SimpleProduct,

    /**
     * The SimpleTag model constructor.
     * @property {module:model/SimpleTag}
     */
    SimpleTag,

    /**
     * The SimpleUser model constructor.
     * @property {module:model/SimpleUser}
     */
    SimpleUser,

    /**
     * The StageDetails model constructor.
     * @property {module:model/StageDetails}
     */
    StageDetails,

    /**
     * The SubscriptionPlan model constructor.
     * @property {module:model/SubscriptionPlan}
     */
    SubscriptionPlan,

    /**
     * The TagId model constructor.
     * @property {module:model/TagId}
     */
    TagId,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
     * The TaskList model constructor.
     * @property {module:model/TaskList}
     */
    TaskList,

    /**
     * The TaskStatus model constructor.
     * @property {module:model/TaskStatus}
     */
    TaskStatus,

    /**
     * The TaskStatusList model constructor.
     * @property {module:model/TaskStatusList}
     */
    TaskStatusList,

    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction,

    /**
     * The TransactionList model constructor.
     * @property {module:model/TransactionList}
     */
    TransactionList,

    /**
     * The UpsertContact model constructor.
     * @property {module:model/UpsertContact}
     */
    UpsertContact,

    /**
    * The AppointmentApi service constructor.
    * @property {module:api/AppointmentApi}
    */
    AppointmentApi,

    /**
    * The CampaignApi service constructor.
    * @property {module:api/CampaignApi}
    */
    CampaignApi,

    /**
    * The ContactApi service constructor.
    * @property {module:api/ContactApi}
    */
    ContactApi,

    /**
    * The ECommerceApi service constructor.
    * @property {module:api/ECommerceApi}
    */
    ECommerceApi,

    /**
    * The OpportunityApi service constructor.
    * @property {module:api/OpportunityApi}
    */
    OpportunityApi,

    /**
    * The ProductApi service constructor.
    * @property {module:api/ProductApi}
    */
    ProductApi,

    /**
    * The RESTHooksApi service constructor.
    * @property {module:api/RESTHooksApi}
    */
    RESTHooksApi,

    /**
    * The TaskApi service constructor.
    * @property {module:api/TaskApi}
    */
    TaskApi
};
