/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.CampaignApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CampaignApi', function() {
    describe('addContactsToCampaignSequenceUsingPOST', function() {
      it('should call addContactsToCampaignSequenceUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addContactsToCampaignSequenceUsingPOST
        //instance.addContactsToCampaignSequenceUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addContactsToCampaignSequenceUsingPOST1', function() {
      it('should call addContactsToCampaignSequenceUsingPOST1 successfully', function(done) {
        //uncomment below and update the code to test addContactsToCampaignSequenceUsingPOST1
        //instance.addContactsToCampaignSequenceUsingPOST1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllCampaignsUsingGET', function() {
      it('should call getAllCampaignsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllCampaignsUsingGET
        //instance.getAllCampaignsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCampaignUsingGET', function() {
      it('should call getCampaignUsingGET successfully', function(done) {
        //uncomment below and update the code to test getCampaignUsingGET
        //instance.getCampaignUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeContactsFromCampaignSequenceUsingDELETE', function() {
      it('should call removeContactsFromCampaignSequenceUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test removeContactsFromCampaignSequenceUsingDELETE
        //instance.removeContactsFromCampaignSequenceUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeContactsFromCampaignSequenceUsingDELETE1', function() {
      it('should call removeContactsFromCampaignSequenceUsingDELETE1 successfully', function(done) {
        //uncomment below and update the code to test removeContactsFromCampaignSequenceUsingDELETE1
        //instance.removeContactsFromCampaignSequenceUsingDELETE1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
