/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.ECommerceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ECommerceApi', function() {
    describe('loadOrderUsingGET', function() {
      it('should call loadOrderUsingGET successfully', function(done) {
        //uncomment below and update the code to test loadOrderUsingGET
        //instance.loadOrderUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUsingGET1', function() {
      it('should call searchUsingGET1 successfully', function(done) {
        //uncomment below and update the code to test searchUsingGET1
        //instance.searchUsingGET1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUsingGET2', function() {
      it('should call searchUsingGET2 successfully', function(done) {
        //uncomment below and update the code to test searchUsingGET2
        //instance.searchUsingGET2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('transactionByIdUsingGET', function() {
      it('should call transactionByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test transactionByIdUsingGET
        //instance.transactionByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('transactionsForOrderUsingGET', function() {
      it('should call transactionsForOrderUsingGET successfully', function(done) {
        //uncomment below and update the code to test transactionsForOrderUsingGET
        //instance.transactionsForOrderUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
