/**
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new InfusionsoftRestApi.RESTHooksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RESTHooksApi', function() {
    describe('createAHookSubscription', function() {
      it('should call createAHookSubscription successfully', function(done) {
        //uncomment below and update the code to test createAHookSubscription
        //instance.createAHookSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAHookSubscription', function() {
      it('should call deleteAHookSubscription successfully', function(done) {
        //uncomment below and update the code to test deleteAHookSubscription
        //instance.deleteAHookSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listHookEventTypes', function() {
      it('should call listHookEventTypes successfully', function(done) {
        //uncomment below and update the code to test listHookEventTypes
        //instance.listHookEventTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listStoredHookSubscriptions', function() {
      it('should call listStoredHookSubscriptions successfully', function(done) {
        //uncomment below and update the code to test listStoredHookSubscriptions
        //instance.listStoredHookSubscriptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('retrieveAHookSubscription', function() {
      it('should call retrieveAHookSubscription successfully', function(done) {
        //uncomment below and update the code to test retrieveAHookSubscription
        //instance.retrieveAHookSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAHookSubscription', function() {
      it('should call updateAHookSubscription successfully', function(done) {
        //uncomment below and update the code to test updateAHookSubscription
        //instance.updateAHookSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyAHookSubscription', function() {
      it('should call verifyAHookSubscription successfully', function(done) {
        //uncomment below and update the code to test verifyAHookSubscription
        //instance.verifyAHookSubscription(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
